In [1]:
import numpy as np
matriz_3x3 = np.arange(9).reshape(3,3)

In [2]:
print(matriz_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
matriz_identidade = np.identity(6)
print(matriz_identidade)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
